name: CI básico

on:
  push:

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola, este es mi primer pipeline"

      - name: Forzar error
        run: exit 1
